# Site settings
name: Markussens Studiefond
description: "Stiftelsen Markussens Studiefond"
url: "http://markussens.se"

# Display settings
markdown: kramdown
permalink: pretty

# Sass
sass:
  style: :compressed
  sass_dir: _sass
